      - name: Guardar CSV en el repositorio
        run: |
          git config --global user.email "tu-email@example.com"
          git config --global user.name "TuNombre"
          git add historial_portafolio.csv
          git commit -m "Actualizar historial_portafolio - ${{ github.run_number }}"
          git push


